### ISSUE TITLE
Change My Project Design to an informative format

### ISSUE THREAD

**Issue by VedantKhairnar** [VedantKhairnar/VedantKhairnar.github.io#1]

**Comment by aritrochakraborty29** [comment]
Hello sir.. I want to do this.. 
can you please explain me about your requirement..?

**Comment by VedantKhairnar** [comment]
@aritrochakraborty29 Feel free to do it!!
Its like the project showcase now isnt informativ at all..All it has got is a poster.. It would be great if it has some cool cards for projects
